api:
  build:
    context: ./backend
    dockerfile: Dockerfile
  ports:
    - "8080:8080"
    - "8081:8081"
  volumes:
    - ./backend:/app
    - /app/bin
    - /app/obj
  depends_on:
    - db
  environment:
    - ConnectionStrings__localhost=Server=db,1433;Database=RSMApp;User Id=sa;Password=ThangTa19@;Encrypt=false
    - ASPNETCORE_URLS=http://+:8080
    - ASPNETCORE_ENVIRONMENT=Development
  # Enable Visual Studio debugging
  entrypoint: ["tail", "-f", "/dev/null"]
